### PR TITLE
The most safest changes until now keku

### PR DESCRIPTION
**Pull request by ryuunosukeyoshi**
Will meld more later

### CODE REVIEW

**Comment by Zephoro** [comment]
Squashed kek

**Comment by IamJoker03** [comment]
@Zephoro lmao

**Comment by ryuunosukeyoshi** [comment]
@Zephoro Keku

**Comment by Zephoro** [comment]
@ryuunosukeyoshi Me gonna squash all your future pull requests :3

**Comment by krasCGQ** [comment]
I sense future possibility of kang later @Zephoro
🏃🏃🏃🏃🏃🏃🏃

**Comment by Zephoro** [comment]
@krasCGQ 😏😏😏

**Pull request merged**
